In [1]:
import pandas as pd

In [30]:
df = pd.read_parquet("../data/coordinates/Portugal/Lisbon.parquet")

In [28]:
def convert_df(d):
    return pd.DataFrame(d,index=[0])

In [12]:
df.places[0]

{'english_name': 'Kala',
 'latitude': 40.706194,
 'longitude': 19.944444,
 'name': 'Berat Castle',
 'postal_code': '5001'}

In [26]:
df.places[1]

{'english_name': 'Mangalem',
 'latitude': 40.708056,
 'longitude': 19.940278,
 'name': 'Mangalem Quarter',
 'postal_code': '5001'}

In [31]:
places_df = pd.json_normalize(df['places'])

places_df

,latitude,longitude,name,postal_code,translation
0,38.6916,-9.2151,Torre de Belém,1400-206,Belém Tower
1,38.6979,-9.2067,Mosteiro dos Jerónimos,1400-209,Jerónimos Monastery
2,38.7142,-9.1324,Castelo de São Jorge,1100-129,Saint George Castle
3,38.6888,-9.1779,Ponte 25 de Abril,1098-001,25th of April Bridge
4,38.7340,-9.1671,Aqueduto das Águas Livres,1070-051,Aqueduct of Free Waters
5,38.7684,-9.0938,Lisbon Oceanarium,1990-005,Oceanário de Lisboa
6,38.7331,-9.1524,Fundação Calouste Gulbenkian,1067-001,Calouste Gulbenkian Foundation
7,38.7118,-9.1390,Elevador de Santa Justa,1100-484,Santa Justa Elevator
8,38.7113,-9.1433,Bairro Alto,1200-109,High District
9,38.7072,-9.1369,Praça do Comércio,1149-014,Commerce Square
10,38.7147,-9.1621,Basílica da Estrela,1250-096,Star Basilica
11,38.7718,-9.0951,Parque das Nações,1990-223,Nations' Park
12,38.7025,-9.2006,Palácio Nacional da Ajuda,1300-018,Ajuda National Palace
13,38.7182,-9.1031,Museu Nacional do Azulejo,1300-408,National Tile Museum
14,38.6989,-9.1823,"Museu de Arte, Arquitetura e Tecnologia",1300-010,"Museum of Art, Architecture and Technology"
15,38.7266,-9.1533,Gulbenkian Park,1070-051,Parque Eduardo VII
16,38.6941,-9.2057,Museu Coleção Berardo,1449-003,Berardo Collection Museum
17,38.7094,-9.1373,Casa dos Bicos,1100-243,House of Spikes
18,38.7149,-9.1337,Museu do Fado,1100-200,Fado Museum
19,38.7063,-9.1548,Museu Nacional de Arte Antiga,1249-017,National Museum of Ancient Art
20,38.7022,-9.1689,Museu do Oriente,1350-362,Orient Museum
21,38.7103,-9.1449,Praça Luís de Camões,1200-243,Luís de Camões Square
22,38.7138,-9.1604,Jardim da Estrela,1200-667,Star Garden
23,38.7153,-9.1484,Museu Nacional do Teatro e da Dança,1200-635,National Museum of Theatre and Dance
24,38.7056,-9.1843,Museu da Água,1300-605,Water Museum
25,38.6978,-9.1979,Museu Nacional dos Coches,1300-004,National Coach Museum
26,38.7143,-9.1436,Elevador da Glória,1250-114,Gloria Elevator
27,38.7410,-9.1580,Casa-Museu Dr. Anastácio Gonçalves,1600-011,Dr. Anastácio Gonçalves House-Museum
28,38.7129,-9.1412,MUDE - Museu do Design e da Moda,1200-083,MUDE - Museum of Design and Fashion
29,38.7140,-9.1496,Museu de Artes Decorativas Portuguesas,1249-009,Museum of Portuguese Decorative Arts

In [ ]:

# Merge the original dataframe with the places dataframe on the index
result_df = df.merge(places_df, left_index=True, right_index=True)

# Drop the original places column
result_df.drop('places', axis=1, inplace=True)

print(result_df)
This code will create a new dataframe places_df by normalizing the "places" column using json_normalize(). Then, it merges the original dataframe df with places_df on their indices using merge(). Finally, it drops the original "places" column using drop().

The resulting dataframe `result

In [32]:
ds = pd.read_csv("../ds_rs.csv")
sample_ds = ds.sample(300,random_state=42)

esco_df = pd.read_csv("skills_fr.csv")
esco_df.preferredLabel = esco_df.preferredLabel.apply(remove_parenthesis)

def remove_html(text_with_markup):
    soup = BeautifulSoup(text_with_markup, 'html.parser')
    text_without_markup = soup.get_text()
    text_without_special_chars = re.sub(r'\s+', ' ', text_without_markup)
    return text_without_special_chars


def french_stem_dataframe(df, column_name,stem_column_name="stemmed"):
    # Tokenize the text and remove SpaCy French stopwords and punctuation
    
    copy_df = deepcopy(df)
    doc = copy_df[column_name].apply(remove_html)
    doc = doc.apply(nlp)
    filtered_words = doc.apply(lambda x: [token.text for token in x if not token.is_punct])

    # Stem each remaining word in the filtered list
    stemmed_words = filtered_words.apply(lambda x: [stemmer.stem(word.replace("\n"," ").replace("  "," ")) for word in x])

    # Join the stemmed words back into a single string
    #stemmed_text = stemmed_words.apply(lambda x: " ".join(x))

    # Add a new column named "prepared" to the input DataFrame
    copy_df[stem_column_name] = [word for word in stemmed_words if word != " "]

    return copy_df



sample_ds = french_stem_dataframe(sample_ds,"description","jobs_stemmed")
esco_df = esco_df[["conceptUri","preferredLabel"]]
esco_df = french_stem_dataframe(esco_df,"preferredLabel","skills_stem")




tqdm.pandas()

esco_df["key"] = 0 
sample_ds["key"] = 0

final_df = esco_df.merge(sample_ds,on="key",how="outer")



def get_ngrams_opt(list_of_skills, n):
    # Create a list of n-grams using a list comprehension
    ngrams = [' '.join(list_of_skills[i:i + n]) for i in range(len(list_of_skills) - n + 1)]
    return ngrams

def compare_skill_desc(jobs_lemma,skills_lemma,threshold=90):
    count = 0
    skill = " ".join(skills_lemma)
    ngrams = [' '.join(jobs_lemma[i:i + len(skills_lemma)]) for i in range(len(jobs_lemma) - len(skills_lemma) + 1)]
    if skill in ngrams:
        return 1
    else:
        return 0


tqdm.pandas()
def compare_skills(skills_df,jobs_df):
    skills_df["key"] = 0 
    jobs_df["key"] = 0

    final_df = skills_df.merge(jobs_df,on="key",how="outer")
    final_df['results'] = final_df.progress_apply(lambda x : compare_skill_desc(x["jobs_stemmed"],x["skills_stem"]),axis=1)
    return final_df

final_df = compare_skills(esco_df,sample_ds)

def generate_results(final_df,skills_df,skill_column=""):
    final_df["joined_skills_stem"] = final_df.skills_stem.apply(lambda x:" ".join(x))
    skills_df["joined_skills_stem"] = skills_df.skills_stem.apply(lambda x:" ".join(x))
    top_50 = final_df.groupby(by="joined_skills_stem").sum().sort_values(by="results",ascending=False)[:51]
    top_50 = top_50.reset_index()
    top_50 = top_50.loc[top_50.joined_skills_stem != ""]
    top_50 = top_50.merge(skills_df,on="joined_skills_stem",how="left")
    top_50.drop_duplicates(subset=["joined_skills_stem"],inplace=True)
    top_50.reset_index(inplace=True,drop=True)
    top_50 =  top_50[[skill_column,"results"]]
    top_50.columns = ["skill","results"]
    return top_50

top_50_esco = generate_results(final_df,esco_df,skill_column="preferredLabel")

FileNotFoundError: [Errno 2] No such file or directory: '../ds_rs.csv'